# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(831, 484)
        self.groupBoxTest = QtWidgets.QGroupBox(Dialog)
        self.groupBoxTest.setGeometry(QtCore.QRect(20, 10, 151, 161))
        self.groupBoxTest.setCheckable(True)
        self.groupBoxTest.setChecked(False)
        self.groupBoxTest.setObjectName("groupBoxTest")
        self.radioButtonTest1 = QtWidgets.QRadioButton(self.groupBoxTest)
        self.radioButtonTest1.setGeometry(QtCore.QRect(20, 30, 117, 22))
        self.radioButtonTest1.setObjectName("radioButtonTest1")
        self.radioButtonTest2 = QtWidgets.QRadioButton(self.groupBoxTest)
        self.radioButtonTest2.setGeometry(QtCore.QRect(20, 60, 117, 22))
        self.radioButtonTest2.setObjectName("radioButtonTest2")
        self.labelTest = QtWidgets.QLabel(self.groupBoxTest)
        self.labelTest.setGeometry(QtCore.QRect(10, 90, 131, 17))
        self.labelTest.setObjectName("labelTest")
        self.groupBoxClick = QtWidgets.QGroupBox(Dialog)
        self.groupBoxClick.setGeometry(QtCore.QRect(190, 10, 291, 221))
        self.groupBoxClick.setObjectName("groupBoxClick")
        self.lineEditName = QtWidgets.QLineEdit(self.groupBoxClick)
        self.lineEditName.setGeometry(QtCore.QRect(140, 30, 113, 27))
        self.lineEditName.setFrame(True)
        self.lineEditName.setObjectName("lineEditName")
        self.labelRespond = QtWidgets.QLabel(self.groupBoxClick)
        self.labelRespond.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.labelRespond.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRespond.setObjectName("labelRespond")
        self.pushButton = QtWidgets.QPushButton(self.groupBoxClick)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(20, 70, 81, 41))
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(False)
        self.pushButton.setProperty("Click1", False)
        self.pushButton.setObjectName("pushButton")
        self.pushButtonKeep = QtWidgets.QPushButton(self.groupBoxClick)
        self.pushButtonKeep.setGeometry(QtCore.QRect(20, 140, 81, 41))
        self.pushButtonKeep.setAutoRepeat(True)
        self.pushButtonKeep.setObjectName("pushButtonKeep")
        self.labelRespondKeep = QtWidgets.QLabel(self.groupBoxClick)
        self.labelRespondKeep.setGeometry(QtCore.QRect(140, 150, 121, 20))
        self.labelRespondKeep.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRespondKeep.setObjectName("labelRespondKeep")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setGeometry(QtCore.QRect(470, 10, 341, 441))
        self.toolBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 339, 377))
        self.page.setObjectName("page")
        self.pushButtonStrInput = QtWidgets.QPushButton(self.page)
        self.pushButtonStrInput.setGeometry(QtCore.QRect(20, 0, 99, 27))
        self.pushButtonStrInput.setObjectName("pushButtonStrInput")
        self.pushButtonIntInput = QtWidgets.QPushButton(self.page)
        self.pushButtonIntInput.setGeometry(QtCore.QRect(20, 40, 99, 27))
        self.pushButtonIntInput.setObjectName("pushButtonIntInput")
        self.lineEditRespondStr = QtWidgets.QLineEdit(self.page)
        self.lineEditRespondStr.setGeometry(QtCore.QRect(160, 0, 113, 27))
        self.lineEditRespondStr.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditRespondStr.setReadOnly(True)
        self.lineEditRespondStr.setObjectName("lineEditRespondStr")
        self.lineEditRespondInt = QtWidgets.QLineEdit(self.page)
        self.lineEditRespondInt.setGeometry(QtCore.QRect(160, 40, 113, 27))
        self.lineEditRespondInt.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditRespondInt.setReadOnly(True)
        self.lineEditRespondInt.setObjectName("lineEditRespondInt")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 339, 377))
        self.page_2.setObjectName("page_2")
        self.pushButtonAptUpdate = QtWidgets.QPushButton(self.page_2)
        self.pushButtonAptUpdate.setGeometry(QtCore.QRect(10, 10, 99, 27))
        self.pushButtonAptUpdate.setObjectName("pushButtonAptUpdate")
        self.listWidgetApt = QtWidgets.QListWidget(self.page_2)
        self.listWidgetApt.setGeometry(QtCore.QRect(10, 50, 321, 141))
        self.listWidgetApt.setObjectName("listWidgetApt")
        self.plainTextEditApt = QtWidgets.QPlainTextEdit(self.page_2)
        self.plainTextEditApt.setGeometry(QtCore.QRect(10, 200, 321, 171))
        self.plainTextEditApt.setDocumentTitle("")
        self.plainTextEditApt.setReadOnly(True)
        self.plainTextEditApt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEditApt.setBackgroundVisible(False)
        self.plainTextEditApt.setObjectName("plainTextEditApt")
        self.toolBox.addItem(self.page_2, "")
        self.groupBoxClick.raise_()
        self.groupBoxTest.raise_()
        self.toolBox.raise_()

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBoxTest.setTitle(_translate("Dialog", "TestBox"))
        self.radioButtonTest1.setText(_translate("Dialog", "Test1"))
        self.radioButtonTest2.setText(_translate("Dialog", "Test2"))
        self.labelTest.setText(_translate("Dialog", "Display CheckBox"))
        self.groupBoxClick.setTitle(_translate("Dialog", "ClickBox"))
        self.labelRespond.setText(_translate("Dialog", "DisplayClick"))
        self.pushButton.setText(_translate("Dialog", "Click"))
        self.pushButtonKeep.setText(_translate("Dialog", "Keep"))
        self.labelRespondKeep.setText(_translate("Dialog", "Display Keep"))
        self.pushButtonStrInput.setText(_translate("Dialog", "Input Str"))
        self.pushButtonIntInput.setText(_translate("Dialog", "Input Int"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Prompt Input"))
        self.pushButtonAptUpdate.setText(_translate("Dialog", "Update"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("Dialog", "Apt Update"))

